---
services:
  flask-app-1:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5000
    networks:
      - pangolin
  flask-app-2:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5001
    networks:
      - pangolin
  flask-app-3:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5002
    networks:
      - pangolin

networks:
  pangolin:
    external: true