---
services:
  sugar-monitor-1:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5000
    networks:
      - pangolin
  sugar-monitor-2:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5001
    networks:
      - pangolin
  sugar-monitor-3:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5002
    networks:
      - pangolin

networks:
  pangolin:
    external: true